package common.data.config;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBException;

import common.data.Configuration;
import common.data.Connection;
import common.data.DataSource;
import common.data.DataSources;
import common.data.configuration.XMLConfiguration;
import common.data.configuration.XMLConnection;
import common.data.configuration.XMLConnections;
import common.data.type.COMPONENT_TYPE;
import common.transformer.XMLConfigurationTransformer;
import common.transformer.XMLConnectionTransformer;
import common.transformer.XMLDataSourceTransformer;
import common.transformer.XMLParser;

public class UtilsConfiguration {

    private static final String PATH_TO_CONFIG_FILE = "src/main/resources/configuration.xml";

    /**
     * Method for retrieving a set of connection data.
     * 
     */
    public static List<Connection> getConnections(COMPONENT_TYPE component) throws MalformedURLException, JAXBException {

        final XMLConnectionTransformer transformer = new XMLConnectionTransformer();

        final List<Connection> connection = new ArrayList<Connection>();

        for (XMLConnection xMLConnection : loadConnections().getConnection()) {
            if (component.equals(xMLConnection.getComponent())) {
                connection.add(transformer.toRemote(xMLConnection));
            }
        }
        return connection;
    }

    /**
     * Retrieve connection data for the defined configuration management component.
     * 
     */
    public static Connection getCMConnection() throws MalformedURLException, JAXBException {
        final List<Connection> connections = getConnections(COMPONENT_TYPE.CONFIGURATION_MANAGEMENT);

        if (null != connections && connections.size() > 0) {
            return connections.get(0);
        } else {
            return null;
        }
    }

    /**
     * Retrieve a set of connection data for the defined event processing components.
     */
    public static List<Connection> getEPConnection() throws MalformedURLException, JAXBException {

        return getConnections(COMPONENT_TYPE.EVENT_PROCESSING);
    }

    /**
     * Retrieve a set of connection data for the defined iot components.
     */
    public static Connection getIoTDeviceConnection() throws MalformedURLException, JAXBException {

        final List<Connection> connections = getConnections(COMPONENT_TYPE.IOT_DEVICE);

        if (null != connections && connections.size() > 0) {
            return connections.get(0);
        } else {
            return null;
        }
    }

    /**
     * Retrieve all connection data.
     */
    public static XMLConnections loadConnections() throws MalformedURLException, JAXBException {

        final XMLConfiguration xMLconfiguration = loadConfigurationNative(PATH_TO_CONFIG_FILE);

        return xMLconfiguration.getConnections();
    }

    /**
     * Retrieve all measurement data.
     */
    public static DataSources loadMeasurementData() throws MalformedURLException, JAXBException {

        final XMLConfiguration xMLconfiguration = loadConfigurationNative(PATH_TO_CONFIG_FILE);
        final XMLDataSourceTransformer transformer = new XMLDataSourceTransformer();

        List<DataSource> remote = transformer.toRemote(xMLconfiguration.getDataSources().getDataSource());

        DataSources measurementData = new DataSources();
        measurementData.add(remote);

        return measurementData;
    }

    /**
     * Load and unmarshal xml configuration file. Return native data structure generated by xsd definition.
     */
    public static XMLConfiguration loadConfigurationNative(String pathToConfigFile) throws MalformedURLException, JAXBException {

        final File configurationFile = new File(pathToConfigFile);

        URI configurationURI = configurationFile.toURI();
        configurationURI = configurationURI.normalize();

        return XMLParser.unmarshal(configurationURI);
    }

    /**
     * Load configuration.
     */
    public static Configuration loadConfiguration() throws MalformedURLException, JAXBException {

        return UtilsConfiguration.loadConfiguration(PATH_TO_CONFIG_FILE);
    }

    public static Configuration loadConfiguration(String pathToConfigFile) throws MalformedURLException, JAXBException {

        final XMLConfiguration loadConfigurationNative = UtilsConfiguration.loadConfigurationNative(pathToConfigFile);

        final XMLConfigurationTransformer transformer = new XMLConfigurationTransformer();

        return transformer.toRemote(loadConfigurationNative);

    }

    /**
     * Save configuration. Pass native data structure generated by xsd definition.
     */
    public static void saveConfigurationNative(XMLConfiguration configuration, String pathToConfigFile) throws JAXBException {

        final File configurationFile = new File(pathToConfigFile);

        XMLParser.marshal(configuration, configurationFile);

    }

    /**
     * Save configuration.
     */
    public static void saveConfiguration(Configuration configuration) throws JAXBException {

        UtilsConfiguration.saveConfiguration(configuration, PATH_TO_CONFIG_FILE);

    }

    public static void saveConfiguration(Configuration configuration, String pathToConfigFile) throws JAXBException {
        final XMLConfigurationTransformer transformer = new XMLConfigurationTransformer();

        UtilsConfiguration.saveConfigurationNative(transformer.toLocal(configuration), pathToConfigFile);
    }

}
